[project]
name = "dbt-sentinel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Qamar Raza", email = "raza.qamar@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "duckdb==1.1.3",
    "httpx==0.28.1",
]

[project.scripts]
dbt-sentinel = "dbt_sentinel:main"

[build-system]
requires = ["uv_build>=0.11.3,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.0",
]
